
--------------------------------------------------------
--  Constraints for Table CHITIETHOADON
--------------------------------------------------------

  ALTER TABLE "GON"."CHITIETHOADON" ADD CONSTRAINT "CHITIETHOADON_PK" PRIMARY KEY ("MACHITIETHOADON")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CHITIETVE
--------------------------------------------------------

  ALTER TABLE "GON"."CHITIETVE" MODIFY ("MAVE" NOT NULL ENABLE);
  ALTER TABLE "GON"."CHITIETVE" ADD CONSTRAINT "CHITIETCHUYENBAY_PK" PRIMARY KEY ("MAVE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CHUYENBAY
--------------------------------------------------------

  ALTER TABLE "GON"."CHUYENBAY" MODIFY ("MACB" NOT NULL ENABLE);
  ALTER TABLE "GON"."CHUYENBAY" ADD CONSTRAINT "CHUYENBAY_PK" PRIMARY KEY ("MACB")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DANGNHAP
--------------------------------------------------------

  ALTER TABLE "GON"."DANGNHAP" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "GON"."DANGNHAP" ADD CONSTRAINT "DANGNHAP_PK" PRIMARY KEY ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table HANGMAYBAY
--------------------------------------------------------

  ALTER TABLE "GON"."HANGMAYBAY" MODIFY ("MAHMB" NOT NULL ENABLE);
  ALTER TABLE "GON"."HANGMAYBAY" ADD CONSTRAINT "HANGMAYBAY_PK" PRIMARY KEY ("MAHMB")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table HOADON
--------------------------------------------------------

  ALTER TABLE "GON"."HOADON" ADD CONSTRAINT "HOADON_PK" PRIMARY KEY ("MAHOADON")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table KHACHHANG
--------------------------------------------------------

  ALTER TABLE "GON"."KHACHHANG" MODIFY ("MAKHACHHANG" NOT NULL ENABLE);
  ALTER TABLE "GON"."KHACHHANG" ADD CONSTRAINT "KHACHHANG_PK" PRIMARY KEY ("MAKHACHHANG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table KHUYENMAI
--------------------------------------------------------

  ALTER TABLE "GON"."KHUYENMAI" MODIFY ("MAKM" NOT NULL ENABLE);
  ALTER TABLE "GON"."KHUYENMAI" ADD CONSTRAINT "KHUYENMAI_PK" PRIMARY KEY ("MAKM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SANBAY
--------------------------------------------------------

  ALTER TABLE "GON"."SANBAY" MODIFY ("MASB" NOT NULL ENABLE);
  ALTER TABLE "GON"."SANBAY" ADD CONSTRAINT "SANBAY_PK" PRIMARY KEY ("MASB")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VE
--------------------------------------------------------

  ALTER TABLE "GON"."VE" MODIFY ("MAVE" NOT NULL ENABLE);
  ALTER TABLE "GON"."VE" ADD CONSTRAINT "VE_PK" PRIMARY KEY ("MAVE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CHITIETHOADON
--------------------------------------------------------

  ALTER TABLE "GON"."CHITIETHOADON" ADD CONSTRAINT "MAHOADON_HOADONG_FK" FOREIGN KEY ("MAHOADON")
	  REFERENCES "GON"."HOADON" ("MAHOADON") ON DELETE SET NULL ENABLE;
  ALTER TABLE "GON"."CHITIETHOADON" ADD CONSTRAINT "CTHOADON_CTVE_FK" FOREIGN KEY ("MAVE")
	  REFERENCES "GON"."CHITIETVE" ("MAVE") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CHITIETVE
--------------------------------------------------------

  ALTER TABLE "GON"."CHITIETVE" ADD CONSTRAINT "CT_VE_FK" FOREIGN KEY ("MAVE")
	  REFERENCES "GON"."VE" ("MAVE") ON DELETE CASCADE ENABLE;
  ALTER TABLE "GON"."CHITIETVE" ADD CONSTRAINT "CT_VE_FK_CHUYENBAY_MACB_FK" FOREIGN KEY ("MACB")
	  REFERENCES "GON"."CHUYENBAY" ("MACB") ON DELETE SET NULL ENABLE;
  ALTER TABLE "GON"."CHITIETVE" ADD CONSTRAINT "CHITIETVE_KHACHHANG_MAKHACHHANG_FK" FOREIGN KEY ("MAKHACHHANG")
	  REFERENCES "GON"."KHACHHANG" ("MAKHACHHANG") ON DELETE SET NULL ENABLE;
  ALTER TABLE "GON"."CHITIETVE" ADD CONSTRAINT "CHITIETVE_KHUYENMAI_MAKM_FK" FOREIGN KEY ("KHUYENMAI")
	  REFERENCES "GON"."KHUYENMAI" ("MAKM") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CHUYENBAY
--------------------------------------------------------

  ALTER TABLE "GON"."CHUYENBAY" ADD CONSTRAINT "CHUYENBAY_HANGMAYBAY_MAHMB_FK" FOREIGN KEY ("MAHMB")
	  REFERENCES "GON"."HANGMAYBAY" ("MAHMB") ON DELETE SET NULL ENABLE;
  ALTER TABLE "GON"."CHUYENBAY" ADD CONSTRAINT "CHUYENBAY_SANBAY_MASB_FK" FOREIGN KEY ("DIEMKHOIHANH")
	  REFERENCES "GON"."SANBAY" ("MASB") ON DELETE SET NULL ENABLE;
  ALTER TABLE "GON"."CHUYENBAY" ADD CONSTRAINT "CHUYENBAY_SANBAY_MASB_FK_2" FOREIGN KEY ("DIEMDEN")
	  REFERENCES "GON"."SANBAY" ("MASB") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HOADON
--------------------------------------------------------

  ALTER TABLE "GON"."HOADON" ADD CONSTRAINT "HOADON_KHACHHANG_MAKHACHHANG_FK" FOREIGN KEY ("KHACHHANG")
	  REFERENCES "GON"."KHACHHANG" ("MAKHACHHANG") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VE
--------------------------------------------------------

  ALTER TABLE "GON"."VE" ADD CONSTRAINT "VE_CHUYENBAY_MACB_FK" FOREIGN KEY ("MACB")
	  REFERENCES "GON"."CHUYENBAY" ("MACB") ON DELETE SET NULL ENABLE;
